apiVersion: v1
kind: Pod
metadata:
  name: flask-web
spec:
  containers:
    - name: flask-web
      image: pgrts119/flask_app-web:latest
      ports:
        - containerPort: 5000
      volumeMounts:
        - mountPath: /app/data
          name: db-volume
  volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName: data-pvc