services:
  web:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile  # Use the specified Dockerfile
    container_name: pgrtson1
    image: pgrts119/flaskappdisk:latest
    pull_policy: always    
    volumes:
      - /mnt/disks/gce-containers-mounts/gce-persistent-disks/car-db-disk:/app/data  # Mount car-db-disk to /app/data
      - /mnt/disks/gce-containers-mounts/gce-persistent-disks/model-disk:/app/cbm   # Mount model-disk to /app/cbm
    ports:
      - "80:80"  # Expose Nginx port
      - "8080:8080"  # Expose Gunicorn port for debugging/internal testing
    environment:
      - FLASK_APP=app.py
      - GOOGLE_APPLICATION_CREDENTIALS=/home/mitchag191/strategic-kite-441305-c8-e1facc654573.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
