services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flasky2
    expose:
      - "8000"  # Expose Gunicorn's port inside the container
    volumes:
      - ./cbm:/app/cbm          # Mount cbm folder to /app/cbm in the container
      - ./data:/app/data
    environment:
      - FLASK_APP=app.py 
    # No need to add depends_on here since Nginx doesn't depend on the web service.
    # Nginx will reach out to web after it's up.

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx config file
      - .:/app  # Mount the app code so Nginx can access it for static filesdocker-compose logs flask_app
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - web  # Make sure Nginx waits for the Flask app to be ready


