apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: pgrts119/flask_app-web:latest
          volumeMounts:
            - mountPath: /app/data/car_db.db  # Mount as a file, not a directory
              subPath: car_db.db  # Explicitly mount the file within the PV
              name: car-db-volume
      volumes:
        - name: car-db-volume
          persistentVolumeClaim:
            claimName: car-db-pvc
