apiVersion: v1
kind: PersistentVolume
metadata:
  name: car-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath  
  hostPath:
    path: "C:/Users/pgrts/Desktop/python/car_proj/data/car_db.db"  # Single file