apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: car-db-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath      
  volumeName: car-db-pv
