apiVersion: v1
kind: Service
metadata:
  name: flask-web
spec:
  selector:
    app: flask-web  # The app label must match the Flask app pod label
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP