apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-app-pv
spec:
  capacity:
    storage: 1Gi  # Ensure this matches the PVC size request
  accessModes:
    - ReadWriteOnce  # Ensure this matches the PVC's access mode
  gcePersistentDisk:
    pdName: car-db-disk  # Ensure the disk is created and available in your cloud provider
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain  # Keep this as Retain or set to Delete if needed